apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: big-p
  namespace: staging
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
spec:
  ingressClassName: nginx
  rules:
    - host: stag-be.bewe.tech
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: mern-be-service
                port:
                  number: 4000
    - host: stag-fe.bewe.tech
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: mern-fe-service
                port:
                  number: 3000
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: big-p
  namespace: production
spec:
  ingressClassName: nginx
  rules:
    - host: be.bewe.tech
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: mern-be-service
                port:
                  number: 4000
    - host: fe.bewe.tech
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: mern-fe-service
                port:
                  number: 3000
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: big-p
  namespace: monitoring
spec:
  ingressClassName: nginx
  rules:
    - host: monitoring.bewe.tech
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: grafana
                port:
                  number: 3000