apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mongo-persistent-storage
  namespace: staging
  labels:
    app: mongodb
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 20Gi
  storageClassName: gp2